import Orders from "./Orders";
import Order from "./Order";
import WishList from "./WishList";
import ProfileInfo from "./ProfileInfo";
import EditProfile from "./EditProfile";
import Addresses from './Addresses';
import EditAddress from "./EditAddress";
import NewAddress from "./NewAddress";
import PayMethods from './PayMethods';
export { Addresses, EditAddress, NewAddress, EditProfile,Orders, Order, WishList, ProfileInfo, PayMethods };